### PR TITLE
Allow PHP 8.0

### PR DESCRIPTION
**Pull request by ahilles107**

### CODE REVIEW

**Comment by ahilles107** [comment]
If we want to use php 8.0 then we need to use phpunit 9. But then we loose support for php 7.2 ;( What is your opinion folks?

**Comment by ahilles107** [comment]
PHP 8 travis build will work after new https://github.com/consistence/coding-standard release (https://github.com/consistence/coding-standard/pull/65)

**Comment by mhujer** [comment]
@ahilles107 Hi! Thanks for the PR. I have dropped support for PHP < 7.4 in a separate PR #12.

I've rebased your PR on my changes and added 8.0 to allowed failures (it will fail until the consistence/coding-standard is made compatible). But this library itself works fine on 8.0 (I ran the tests locally)

**Comment by mhujer** [comment]
@ahilles107 tagged as 3.3.0

**Pull request merged**
