### PR TITLE
fix serialization handling of uuid

### PR DESCRIPTION
**Pull request by temp**
It didn't work with xml here - json worked fine.
Code adapted to JMS\Serializer\Handler\DateHandler::serializeDateTime().
Works fine now.

### CODE REVIEW

**Comment by mhujer** [comment]
Thanks! :+1: 

I've merged it manually (https://github.com/mhujer/jms-serializer-uuid/commit/24e419c97160d42e3a9fc0b7ba54c613bb885f4e) and added tests (https://github.com/mhujer/jms-serializer-uuid/commit/a94423ea3e3273aaf9cd8529948050b1d2e097e9).

Can you please verify that the master branch works fine for you? (I'll tag it afterwards).

**Comment by temp** [comment]
Just tested the master locally, looks good! 👍

**Comment by mhujer** [comment]
That was quick! :-)

I've released it as [1.0.1](https://github.com/mhujer/jms-serializer-uuid/releases/tag/1.0.1)

**Comment by temp** [comment]
Great, thanks! 👍

**Pull request closed without merging**
